### ISSUE TITLE
Unable to concatenate ImmutableList to list.

### ISSUE THREAD

**Issue by beruic** [tpisani/django-inspect#1]
I guess this is a Python 3 issue, but have not tested. I get.

```
TypeError: can only concatenate list (not "ImmutableList") to list
```

on line 56 in `inspecting.py` whenever I try to inspect a model.

**Comment by tpisani** [comment]
Hey! Actually it was caused by a change in Django's API (1.8).
It is fixed for now, but it will need more work in future Django releases.
Thanks for reporting and sorry I took this long to reach you.

https://github.com/tpisani/django-inspect/releases/tag/v0.4.1
